using CriusNyx.Util;

/// <summary>
/// Used to store number values generated by source code.
/// Since DevCon doesn't have discrete type for different numbers this could represent an interger or real value.
/// Stored as a decimal.
/// </summary>
/// <param name="value"></param>
public class NumVal(decimal value) : DebugPrint
{
  /// <summary>
  /// Value of the num val
  /// </summary>
  public decimal Value => value;

  public static implicit operator int(NumVal numVal)
  {
    return (int)numVal.Value;
  }

  public static implicit operator decimal(NumVal numVal)
  {
    return numVal.Value;
  }

  public static implicit operator float(NumVal numVal)
  {
    return (float)numVal.Value;
  }

  public static implicit operator double(NumVal numVal)
  {
    return (double)numVal.Value;
  }

  public static NumVal operator -(NumVal a)
  {
    return new NumVal(-a.Value);
  }

  public static NumVal operator +(NumVal a, NumVal b)
  {
    return new NumVal(a.Value + b.Value);
  }

  public static NumVal operator -(NumVal a, NumVal b)
  {
    return new NumVal(a.Value - b.Value);
  }

  public static NumVal operator *(NumVal a, NumVal b)
  {
    return new NumVal(a.Value * b.Value);
  }

  public static NumVal operator /(NumVal a, NumVal b)
  {
    return new NumVal(a.Value / b.Value);
  }

  public static NumVal operator %(NumVal a, NumVal b)
  {
    return new NumVal(a.Value % b.Value);
  }

  public IEnumerable<(string, object)> EnumerateFields()
  {
    return [nameof(Value).With(Value)];
  }

  public override string ToString()
  {
    return value.ToString();
  }
}
